# Generated by Django 2.2.2 on 2019-07-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='centerx',
            field=models.CharField(default='37.3595704', max_length=255),
        ),
        migrations.AddField(
            model_name='bar',
            name='centery',
            field=models.CharField(default='127.105399', max_length=255),
        ),
    ]
