# Generated by Django 2.2.2 on 2019-07-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpick', '0002_auto_20190731_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='bar',
            name='title',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
